apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-pvc-sample
  namespace: argocd
spec:
  destination:
    namespace: longhorn-pvc-sample
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: ./longhorn-pvc-sample
    repoURL: https://github.com/kszpakowski/argo-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
