apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
spec:
  destination:
    namespace: prometheus-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    path: operators/prometheus
    repoURL: https://github.com/kszpakowski/argo-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
