apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-operator
  namespace: argocd
spec:
  destination:
    namespace: tekton-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    path: operators/tekton
    repoURL: https://github.com/kszpakowski/argo-apps.git
    targetRevision: HEAD
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec/preserveUnknownFields
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
